version: '3.3'

services:
  api:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: nodejs
    container_name: think-music_api
    restart: always
    command: npm start
    ports:
      - "3333:3000"
    volumes:
      - ./api:/usr/app
      - ./api/node_modules:/usr/app/node_modules
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db/mongo:/data/db
    container_name: think-music_mongo
